apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aksdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksdemo 
    spec:
      containers:
        - name: aksdemo 
          image: atulmakshelm.azurecr.io/k8sdemo 
          imagePullPolicy: Always
          ports:
          - containerPort: 80
